// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/LukeHagar/plexgo/internal/utils"
	"github.com/LukeHagar/plexgo/models/components"
	"net/http"
)

type DeletePlayQueueItemGlobals struct {
	// Indicates the client accepts the indicated media types
	Accepts *components.Accepts `default:"application/xml" header:"style=simple,explode=false,name=accepts"`
	// An opaque identifier unique to the client
	ClientIdentifier *string `header:"style=simple,explode=false,name=X-Plex-Client-Identifier"`
	// The name of the client product
	Product *string `header:"style=simple,explode=false,name=X-Plex-Product"`
	// The version of the client application
	Version *string `header:"style=simple,explode=false,name=X-Plex-Version"`
	// The platform of the client
	Platform *string `header:"style=simple,explode=false,name=X-Plex-Platform"`
	// The version of the platform
	PlatformVersion *string `header:"style=simple,explode=false,name=X-Plex-Platform-Version"`
	// A relatively friendly name for the client device
	Device *string `header:"style=simple,explode=false,name=X-Plex-Device"`
	// A potentially less friendly identifier for the device model
	Model *string `header:"style=simple,explode=false,name=X-Plex-Model"`
	// The device vendor
	DeviceVendor *string `header:"style=simple,explode=false,name=X-Plex-Device-Vendor"`
	// A friendly name for the client
	DeviceName *string `header:"style=simple,explode=false,name=X-Plex-Device-Name"`
	// The marketplace on which the client application is distributed
	Marketplace *string `header:"style=simple,explode=false,name=X-Plex-Marketplace"`
}

func (d DeletePlayQueueItemGlobals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeletePlayQueueItemGlobals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeletePlayQueueItemGlobals) GetAccepts() *components.Accepts {
	if d == nil {
		return nil
	}
	return d.Accepts
}

func (d *DeletePlayQueueItemGlobals) GetClientIdentifier() *string {
	if d == nil {
		return nil
	}
	return d.ClientIdentifier
}

func (d *DeletePlayQueueItemGlobals) GetProduct() *string {
	if d == nil {
		return nil
	}
	return d.Product
}

func (d *DeletePlayQueueItemGlobals) GetVersion() *string {
	if d == nil {
		return nil
	}
	return d.Version
}

func (d *DeletePlayQueueItemGlobals) GetPlatform() *string {
	if d == nil {
		return nil
	}
	return d.Platform
}

func (d *DeletePlayQueueItemGlobals) GetPlatformVersion() *string {
	if d == nil {
		return nil
	}
	return d.PlatformVersion
}

func (d *DeletePlayQueueItemGlobals) GetDevice() *string {
	if d == nil {
		return nil
	}
	return d.Device
}

func (d *DeletePlayQueueItemGlobals) GetModel() *string {
	if d == nil {
		return nil
	}
	return d.Model
}

func (d *DeletePlayQueueItemGlobals) GetDeviceVendor() *string {
	if d == nil {
		return nil
	}
	return d.DeviceVendor
}

func (d *DeletePlayQueueItemGlobals) GetDeviceName() *string {
	if d == nil {
		return nil
	}
	return d.DeviceName
}

func (d *DeletePlayQueueItemGlobals) GetMarketplace() *string {
	if d == nil {
		return nil
	}
	return d.Marketplace
}

type DeletePlayQueueItemRequest struct {
	// Indicates the client accepts the indicated media types
	Accepts *components.Accepts `default:"application/xml" header:"style=simple,explode=false,name=accepts"`
	// An opaque identifier unique to the client
	ClientIdentifier *string `header:"style=simple,explode=false,name=X-Plex-Client-Identifier"`
	// The name of the client product
	Product *string `header:"style=simple,explode=false,name=X-Plex-Product"`
	// The version of the client application
	Version *string `header:"style=simple,explode=false,name=X-Plex-Version"`
	// The platform of the client
	Platform *string `header:"style=simple,explode=false,name=X-Plex-Platform"`
	// The version of the platform
	PlatformVersion *string `header:"style=simple,explode=false,name=X-Plex-Platform-Version"`
	// A relatively friendly name for the client device
	Device *string `header:"style=simple,explode=false,name=X-Plex-Device"`
	// A potentially less friendly identifier for the device model
	Model *string `header:"style=simple,explode=false,name=X-Plex-Model"`
	// The device vendor
	DeviceVendor *string `header:"style=simple,explode=false,name=X-Plex-Device-Vendor"`
	// A friendly name for the client
	DeviceName *string `header:"style=simple,explode=false,name=X-Plex-Device-Name"`
	// The marketplace on which the client application is distributed
	Marketplace *string `header:"style=simple,explode=false,name=X-Plex-Marketplace"`
	// The ID of the play queue.
	PlayQueueID int64 `pathParam:"style=simple,explode=false,name=playQueueId"`
	// The play queue item ID to delete.
	PlayQueueItemID int64 `pathParam:"style=simple,explode=false,name=playQueueItemId"`
}

func (d DeletePlayQueueItemRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeletePlayQueueItemRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"playQueueId", "playQueueItemId"}); err != nil {
		return err
	}
	return nil
}

func (d *DeletePlayQueueItemRequest) GetAccepts() *components.Accepts {
	if d == nil {
		return nil
	}
	return d.Accepts
}

func (d *DeletePlayQueueItemRequest) GetClientIdentifier() *string {
	if d == nil {
		return nil
	}
	return d.ClientIdentifier
}

func (d *DeletePlayQueueItemRequest) GetProduct() *string {
	if d == nil {
		return nil
	}
	return d.Product
}

func (d *DeletePlayQueueItemRequest) GetVersion() *string {
	if d == nil {
		return nil
	}
	return d.Version
}

func (d *DeletePlayQueueItemRequest) GetPlatform() *string {
	if d == nil {
		return nil
	}
	return d.Platform
}

func (d *DeletePlayQueueItemRequest) GetPlatformVersion() *string {
	if d == nil {
		return nil
	}
	return d.PlatformVersion
}

func (d *DeletePlayQueueItemRequest) GetDevice() *string {
	if d == nil {
		return nil
	}
	return d.Device
}

func (d *DeletePlayQueueItemRequest) GetModel() *string {
	if d == nil {
		return nil
	}
	return d.Model
}

func (d *DeletePlayQueueItemRequest) GetDeviceVendor() *string {
	if d == nil {
		return nil
	}
	return d.DeviceVendor
}

func (d *DeletePlayQueueItemRequest) GetDeviceName() *string {
	if d == nil {
		return nil
	}
	return d.DeviceName
}

func (d *DeletePlayQueueItemRequest) GetMarketplace() *string {
	if d == nil {
		return nil
	}
	return d.Marketplace
}

func (d *DeletePlayQueueItemRequest) GetPlayQueueID() int64 {
	if d == nil {
		return 0
	}
	return d.PlayQueueID
}

func (d *DeletePlayQueueItemRequest) GetPlayQueueItemID() int64 {
	if d == nil {
		return 0
	}
	return d.PlayQueueItemID
}

type DeletePlayQueueItemResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	MediaContainerWithPlaylistMetadata *components.MediaContainerWithPlaylistMetadata
}

func (d *DeletePlayQueueItemResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeletePlayQueueItemResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeletePlayQueueItemResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeletePlayQueueItemResponse) GetMediaContainerWithPlaylistMetadata() *components.MediaContainerWithPlaylistMetadata {
	if d == nil {
		return nil
	}
	return d.MediaContainerWithPlaylistMetadata
}
