// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetFileHashRequest struct {
	// This is the path to the local file, must be prefixed by `file://`
	URL string `queryParam:"style=form,explode=true,name=url"`
	// Item type
	Type *float64 `queryParam:"style=form,explode=true,name=type"`
}

func (g *GetFileHashRequest) GetURL() string {
	if g == nil {
		return ""
	}
	return g.URL
}

func (g *GetFileHashRequest) GetType() *float64 {
	if g == nil {
		return nil
	}
	return g.Type
}

type GetFileHashResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetFileHashResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetFileHashResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetFileHashResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
