// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/LukeHagar/plexgo/models/components"
	"net/http"
)

// GetSectionsMediaContainer - `MediaContainer` is the root element of most Plex API responses. It serves as a generic container for various types of content (Metadata, Hubs, Directories, etc.) and includes pagination information (offset, size, totalSize) when applicable.
// Common attributes: - identifier: Unique identifier for this container - size: Number of items in this response page - totalSize: Total number of items available (for pagination) - offset: Starting index of this page (for pagination)
// The container often "hoists" common attributes from its children. For example, if all tracks in a container share the same album title, the `parentTitle` attribute may appear on the MediaContainer rather than being repeated on each track.
type GetSectionsMediaContainer struct {
	Identifier *string `json:"identifier,omitempty"`
	// The offset of where this container page starts among the total objects available. Also provided in the `X-Plex-Container-Start` header.
	//
	Offset *int64 `json:"offset,omitempty"`
	Size   *int64 `json:"size,omitempty"`
	// The total size of objects available. Also provided in the `X-Plex-Container-Total-Size` header.
	//
	TotalSize *int64                      `json:"totalSize,omitempty"`
	AllowSync *bool                       `json:"allowSync,omitempty"`
	Directory []components.LibrarySection `json:"Directory,omitempty"`
	// Typically just "Plex Library"
	Title1 *string `json:"title1,omitempty"`
}

func (g *GetSectionsMediaContainer) GetIdentifier() *string {
	if g == nil {
		return nil
	}
	return g.Identifier
}

func (g *GetSectionsMediaContainer) GetOffset() *int64 {
	if g == nil {
		return nil
	}
	return g.Offset
}

func (g *GetSectionsMediaContainer) GetSize() *int64 {
	if g == nil {
		return nil
	}
	return g.Size
}

func (g *GetSectionsMediaContainer) GetTotalSize() *int64 {
	if g == nil {
		return nil
	}
	return g.TotalSize
}

func (g *GetSectionsMediaContainer) GetAllowSync() *bool {
	if g == nil {
		return nil
	}
	return g.AllowSync
}

func (g *GetSectionsMediaContainer) GetDirectory() []components.LibrarySection {
	if g == nil {
		return nil
	}
	return g.Directory
}

func (g *GetSectionsMediaContainer) GetTitle1() *string {
	if g == nil {
		return nil
	}
	return g.Title1
}

// GetSectionsResponseBody - OK
type GetSectionsResponseBody struct {
	MediaContainer *GetSectionsMediaContainer `json:"MediaContainer,omitempty"`
}

func (g *GetSectionsResponseBody) GetMediaContainer() *GetSectionsMediaContainer {
	if g == nil {
		return nil
	}
	return g.MediaContainer
}

type GetSectionsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Object  *GetSectionsResponseBody
	Headers map[string][]string
}

func (g *GetSectionsResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetSectionsResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetSectionsResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetSectionsResponse) GetObject() *GetSectionsResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}

func (g *GetSectionsResponse) GetHeaders() map[string][]string {
	if g == nil {
		return map[string][]string{}
	}
	return g.Headers
}
