// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

// Level - An integer log level to write to the PMS log with.
// 0: Error
// 1: Warning
// 2: Info
// 3: Debug
// 4: Verbose
type Level int64

const (
	LevelZero  Level = 0
	LevelOne   Level = 1
	LevelTwo   Level = 2
	LevelThree Level = 3
	LevelFour  Level = 4
)

func (e Level) ToPointer() *Level {
	return &e
}

type LogLineRequest struct {
	// An integer log level to write to the PMS log with.
	// 0: Error
	// 1: Warning
	// 2: Info
	// 3: Debug
	// 4: Verbose
	//
	Level Level `queryParam:"style=form,explode=true,name=level"`
	// The text of the message to write to the log.
	Message string `queryParam:"style=form,explode=true,name=message"`
	// a string indicating the source of the message.
	Source string `queryParam:"style=form,explode=true,name=source"`
}

func (l *LogLineRequest) GetLevel() Level {
	if l == nil {
		return Level(0)
	}
	return l.Level
}

func (l *LogLineRequest) GetMessage() string {
	if l == nil {
		return ""
	}
	return l.Message
}

func (l *LogLineRequest) GetSource() string {
	if l == nil {
		return ""
	}
	return l.Source
}

type LogLineResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (l *LogLineResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *LogLineResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *LogLineResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}
