// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

type GetPlaylistPlaylistsErrors struct {
	Code    *int    `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Status  *int    `json:"status,omitempty"`
}

func (g *GetPlaylistPlaylistsErrors) GetCode() *int {
	if g == nil {
		return nil
	}
	return g.Code
}

func (g *GetPlaylistPlaylistsErrors) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

func (g *GetPlaylistPlaylistsErrors) GetStatus() *int {
	if g == nil {
		return nil
	}
	return g.Status
}

// GetPlaylistUnauthorized - Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
type GetPlaylistUnauthorized struct {
	Errors []GetPlaylistPlaylistsErrors `json:"errors,omitempty"`
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
}

var _ error = &GetPlaylistUnauthorized{}

func (e *GetPlaylistUnauthorized) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type GetPlaylistErrors struct {
	Code    *int    `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Status  *int    `json:"status,omitempty"`
}

func (g *GetPlaylistErrors) GetCode() *int {
	if g == nil {
		return nil
	}
	return g.Code
}

func (g *GetPlaylistErrors) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

func (g *GetPlaylistErrors) GetStatus() *int {
	if g == nil {
		return nil
	}
	return g.Status
}

// GetPlaylistBadRequest - Bad Request - A parameter was not specified, or was specified incorrectly.
type GetPlaylistBadRequest struct {
	Errors []GetPlaylistErrors `json:"errors,omitempty"`
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
}

var _ error = &GetPlaylistBadRequest{}

func (e *GetPlaylistBadRequest) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
