// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

type GetSearchResultsSearchErrors struct {
	Code    *int    `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Status  *int    `json:"status,omitempty"`
}

func (g *GetSearchResultsSearchErrors) GetCode() *int {
	if g == nil {
		return nil
	}
	return g.Code
}

func (g *GetSearchResultsSearchErrors) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

func (g *GetSearchResultsSearchErrors) GetStatus() *int {
	if g == nil {
		return nil
	}
	return g.Status
}

// GetSearchResultsUnauthorized - Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
type GetSearchResultsUnauthorized struct {
	Errors []GetSearchResultsSearchErrors `json:"errors,omitempty"`
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
}

var _ error = &GetSearchResultsUnauthorized{}

func (e *GetSearchResultsUnauthorized) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type GetSearchResultsErrors struct {
	Code    *int    `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Status  *int    `json:"status,omitempty"`
}

func (g *GetSearchResultsErrors) GetCode() *int {
	if g == nil {
		return nil
	}
	return g.Code
}

func (g *GetSearchResultsErrors) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

func (g *GetSearchResultsErrors) GetStatus() *int {
	if g == nil {
		return nil
	}
	return g.Status
}

// GetSearchResultsBadRequest - Bad Request - A parameter was not specified, or was specified incorrectly.
type GetSearchResultsBadRequest struct {
	Errors []GetSearchResultsErrors `json:"errors,omitempty"`
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
}

var _ error = &GetSearchResultsBadRequest{}

func (e *GetSearchResultsBadRequest) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
