// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"net/http"
)

// GetServerIdentityRequestTimeout - Request Timeout
type GetServerIdentityRequestTimeout struct {
	Code    *int    `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
}

var _ error = &GetServerIdentityRequestTimeout{}

func (e *GetServerIdentityRequestTimeout) Error() string {
	if e.Message == nil {
		return "unknown error"
	}

	return *e.Message
}
