// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

type GetSessionHistorySessionsErrors struct {
	Code    *int    `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Status  *int    `json:"status,omitempty"`
}

func (g *GetSessionHistorySessionsErrors) GetCode() *int {
	if g == nil {
		return nil
	}
	return g.Code
}

func (g *GetSessionHistorySessionsErrors) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

func (g *GetSessionHistorySessionsErrors) GetStatus() *int {
	if g == nil {
		return nil
	}
	return g.Status
}

// GetSessionHistoryUnauthorized - Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
type GetSessionHistoryUnauthorized struct {
	Errors []GetSessionHistorySessionsErrors `json:"errors,omitempty"`
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
}

var _ error = &GetSessionHistoryUnauthorized{}

func (e *GetSessionHistoryUnauthorized) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type GetSessionHistoryErrors struct {
	Code    *int    `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Status  *int    `json:"status,omitempty"`
}

func (g *GetSessionHistoryErrors) GetCode() *int {
	if g == nil {
		return nil
	}
	return g.Code
}

func (g *GetSessionHistoryErrors) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

func (g *GetSessionHistoryErrors) GetStatus() *int {
	if g == nil {
		return nil
	}
	return g.Status
}

// GetSessionHistoryBadRequest - Bad Request - A parameter was not specified, or was specified incorrectly.
type GetSessionHistoryBadRequest struct {
	Errors []GetSessionHistoryErrors `json:"errors,omitempty"`
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
}

var _ error = &GetSessionHistoryBadRequest{}

func (e *GetSessionHistoryBadRequest) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
