// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

type GetServerPreferencesServerErrors struct {
	Code    *int64  `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Status  *int64  `json:"status,omitempty"`
}

func (o *GetServerPreferencesServerErrors) GetCode() *int64 {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *GetServerPreferencesServerErrors) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *GetServerPreferencesServerErrors) GetStatus() *int64 {
	if o == nil {
		return nil
	}
	return o.Status
}

// GetServerPreferencesServerResponseBody - Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
type GetServerPreferencesServerResponseBody struct {
	Errors []GetServerPreferencesServerErrors `json:"errors,omitempty"`
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
}

var _ error = &GetServerPreferencesServerResponseBody{}

func (e *GetServerPreferencesServerResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type GetServerPreferencesErrors struct {
	Code    *int64  `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Status  *int64  `json:"status,omitempty"`
}

func (o *GetServerPreferencesErrors) GetCode() *int64 {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *GetServerPreferencesErrors) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *GetServerPreferencesErrors) GetStatus() *int64 {
	if o == nil {
		return nil
	}
	return o.Status
}

// GetServerPreferencesResponseBody - Bad Request - A parameter was not specified, or was specified incorrectly.
type GetServerPreferencesResponseBody struct {
	Errors []GetServerPreferencesErrors `json:"errors,omitempty"`
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
}

var _ error = &GetServerPreferencesResponseBody{}

func (e *GetServerPreferencesResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
