// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

type GetSearchLibraryLibraryErrors struct {
	Code    *int64  `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Status  *int64  `json:"status,omitempty"`
}

func (o *GetSearchLibraryLibraryErrors) GetCode() *int64 {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *GetSearchLibraryLibraryErrors) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *GetSearchLibraryLibraryErrors) GetStatus() *int64 {
	if o == nil {
		return nil
	}
	return o.Status
}

// GetSearchLibraryUnauthorized - Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
type GetSearchLibraryUnauthorized struct {
	Errors []GetSearchLibraryLibraryErrors `json:"errors,omitempty"`
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
}

var _ error = &GetSearchLibraryUnauthorized{}

func (e *GetSearchLibraryUnauthorized) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type GetSearchLibraryErrors struct {
	Code    *int64  `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Status  *int64  `json:"status,omitempty"`
}

func (o *GetSearchLibraryErrors) GetCode() *int64 {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *GetSearchLibraryErrors) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *GetSearchLibraryErrors) GetStatus() *int64 {
	if o == nil {
		return nil
	}
	return o.Status
}

// GetSearchLibraryBadRequest - Bad Request - A parameter was not specified, or was specified incorrectly.
type GetSearchLibraryBadRequest struct {
	Errors []GetSearchLibraryErrors `json:"errors,omitempty"`
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
}

var _ error = &GetSearchLibraryBadRequest{}

func (e *GetSearchLibraryBadRequest) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
