// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

type GetUserFriendsPlexErrors struct {
	Code    *int64  `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Status  *int64  `json:"status,omitempty"`
}

func (o *GetUserFriendsPlexErrors) GetCode() *int64 {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *GetUserFriendsPlexErrors) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *GetUserFriendsPlexErrors) GetStatus() *int64 {
	if o == nil {
		return nil
	}
	return o.Status
}

// GetUserFriendsPlexResponseBody - Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
type GetUserFriendsPlexResponseBody struct {
	Errors []GetUserFriendsPlexErrors `json:"errors,omitempty"`
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
}

var _ error = &GetUserFriendsPlexResponseBody{}

func (e *GetUserFriendsPlexResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type GetUserFriendsErrors struct {
	Code    *int64  `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Status  *int64  `json:"status,omitempty"`
}

func (o *GetUserFriendsErrors) GetCode() *int64 {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *GetUserFriendsErrors) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *GetUserFriendsErrors) GetStatus() *int64 {
	if o == nil {
		return nil
	}
	return o.Status
}

// GetUserFriendsResponseBody - Bad Request - A parameter was not specified, or was specified incorrectly.
type GetUserFriendsResponseBody struct {
	Errors []GetUserFriendsErrors `json:"errors,omitempty"`
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
}

var _ error = &GetUserFriendsResponseBody{}

func (e *GetUserFriendsResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
