// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

type StartUniversalTranscodeVideoErrors struct {
	Code    *int64  `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Status  *int64  `json:"status,omitempty"`
}

func (o *StartUniversalTranscodeVideoErrors) GetCode() *int64 {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *StartUniversalTranscodeVideoErrors) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *StartUniversalTranscodeVideoErrors) GetStatus() *int64 {
	if o == nil {
		return nil
	}
	return o.Status
}

// StartUniversalTranscodeUnauthorized - Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
type StartUniversalTranscodeUnauthorized struct {
	Errors []StartUniversalTranscodeVideoErrors `json:"errors,omitempty"`
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
}

var _ error = &StartUniversalTranscodeUnauthorized{}

func (e *StartUniversalTranscodeUnauthorized) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type StartUniversalTranscodeErrors struct {
	Code    *int64  `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Status  *int64  `json:"status,omitempty"`
}

func (o *StartUniversalTranscodeErrors) GetCode() *int64 {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *StartUniversalTranscodeErrors) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *StartUniversalTranscodeErrors) GetStatus() *int64 {
	if o == nil {
		return nil
	}
	return o.Status
}

// StartUniversalTranscodeBadRequest - Bad Request - A parameter was not specified, or was specified incorrectly.
type StartUniversalTranscodeBadRequest struct {
	Errors []StartUniversalTranscodeErrors `json:"errors,omitempty"`
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
}

var _ error = &StartUniversalTranscodeBadRequest{}

func (e *StartUniversalTranscodeBadRequest) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
