// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

type StartTaskButlerErrors struct {
	Code    *int64  `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Status  *int64  `json:"status,omitempty"`
}

func (o *StartTaskButlerErrors) GetCode() *int64 {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *StartTaskButlerErrors) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *StartTaskButlerErrors) GetStatus() *int64 {
	if o == nil {
		return nil
	}
	return o.Status
}

// StartTaskUnauthorized - Unauthorized - Returned if the X-Plex-Token is missing from the header or query.
type StartTaskUnauthorized struct {
	Errors []StartTaskButlerErrors `json:"errors,omitempty"`
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
}

var _ error = &StartTaskUnauthorized{}

func (e *StartTaskUnauthorized) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type StartTaskErrors struct {
	Code    *int64  `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Status  *int64  `json:"status,omitempty"`
}

func (o *StartTaskErrors) GetCode() *int64 {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *StartTaskErrors) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *StartTaskErrors) GetStatus() *int64 {
	if o == nil {
		return nil
	}
	return o.Status
}

// StartTaskBadRequest - Bad Request - A parameter was not specified, or was specified incorrectly.
type StartTaskBadRequest struct {
	Errors []StartTaskErrors `json:"errors,omitempty"`
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
}

var _ error = &StartTaskBadRequest{}

func (e *StartTaskBadRequest) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
